/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRopaRouteImport } from './routes/app.ropa'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRegulationsRouteImport } from './routes/app.regulations'
import { Route as AppNoticesRouteImport } from './routes/app.notices'
import { Route as AppGrievanceRouteImport } from './routes/app.grievance'
import { Route as AppDsarRouteImport } from './routes/app.dsar'
import { Route as AppDpaReviewerRouteImport } from './routes/app.dpa-reviewer'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppControlsRouteImport } from './routes/app.controls'
import { Route as AppAssessmentsRouteImport } from './routes/app.assessments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRopaRoute = AppRopaRouteImport.update({
  id: '/ropa',
  path: '/ropa',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegulationsRoute = AppRegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppGrievanceRoute = AppGrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => AppRoute,
} as any)
const AppDsarRoute = AppDsarRouteImport.update({
  id: '/dsar',
  path: '/dsar',
  getParentRoute: () => AppRoute,
} as any)
const AppDpaReviewerRoute = AppDpaReviewerRouteImport.update({
  id: '/dpa-reviewer',
  path: '/dpa-reviewer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppControlsRoute = AppControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/controls': typeof AppControlsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dpa-reviewer': typeof AppDpaReviewerRoute
  '/app/dsar': typeof AppDsarRoute
  '/app/grievance': typeof AppGrievanceRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/regulations': typeof AppRegulationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/ropa': typeof AppRopaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/controls': typeof AppControlsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dpa-reviewer': typeof AppDpaReviewerRoute
  '/app/dsar': typeof AppDsarRoute
  '/app/grievance': typeof AppGrievanceRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/regulations': typeof AppRegulationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/ropa': typeof AppRopaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/controls': typeof AppControlsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dpa-reviewer': typeof AppDpaReviewerRoute
  '/app/dsar': typeof AppDsarRoute
  '/app/grievance': typeof AppGrievanceRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/regulations': typeof AppRegulationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/ropa': typeof AppRopaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/assessments'
    | '/app/controls'
    | '/app/dashboard'
    | '/app/dpa-reviewer'
    | '/app/dsar'
    | '/app/grievance'
    | '/app/notices'
    | '/app/regulations'
    | '/app/reports'
    | '/app/ropa'
    | '/app/settings'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/assessments'
    | '/app/controls'
    | '/app/dashboard'
    | '/app/dpa-reviewer'
    | '/app/dsar'
    | '/app/grievance'
    | '/app/notices'
    | '/app/regulations'
    | '/app/reports'
    | '/app/ropa'
    | '/app/settings'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/assessments'
    | '/app/controls'
    | '/app/dashboard'
    | '/app/dpa-reviewer'
    | '/app/dsar'
    | '/app/grievance'
    | '/app/notices'
    | '/app/regulations'
    | '/app/reports'
    | '/app/ropa'
    | '/app/settings'
    | '/app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ropa': {
      id: '/app/ropa'
      path: '/ropa'
      fullPath: '/app/ropa'
      preLoaderRoute: typeof AppRopaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/regulations': {
      id: '/app/regulations'
      path: '/regulations'
      fullPath: '/app/regulations'
      preLoaderRoute: typeof AppRegulationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notices': {
      id: '/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grievance': {
      id: '/app/grievance'
      path: '/grievance'
      fullPath: '/app/grievance'
      preLoaderRoute: typeof AppGrievanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dsar': {
      id: '/app/dsar'
      path: '/dsar'
      fullPath: '/app/dsar'
      preLoaderRoute: typeof AppDsarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dpa-reviewer': {
      id: '/app/dpa-reviewer'
      path: '/dpa-reviewer'
      fullPath: '/app/dpa-reviewer'
      preLoaderRoute: typeof AppDpaReviewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/controls': {
      id: '/app/controls'
      path: '/controls'
      fullPath: '/app/controls'
      preLoaderRoute: typeof AppControlsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments': {
      id: '/app/assessments'
      path: '/assessments'
      fullPath: '/app/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppControlsRoute: typeof AppControlsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDpaReviewerRoute: typeof AppDpaReviewerRoute
  AppDsarRoute: typeof AppDsarRoute
  AppGrievanceRoute: typeof AppGrievanceRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppRegulationsRoute: typeof AppRegulationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRopaRoute: typeof AppRopaRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppControlsRoute: AppControlsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDpaReviewerRoute: AppDpaReviewerRoute,
  AppDsarRoute: AppDsarRoute,
  AppGrievanceRoute: AppGrievanceRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppRegulationsRoute: AppRegulationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRopaRoute: AppRopaRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
